apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micser-prod-ingress
  namespace: production
  labels:
    app: micser-prod
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  tls:
  - hosts:
    - api.mycompany.com
    secretName: micser-prod-tls
  rules:
  - host: api.mycompany.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: micser-prod
            port:
              number: 80